////If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
//Find the sum of all the multiples of 3 or 5 below 1000.

//Project Euler: Problem 1

var summer = function() {
  var counter = 0;
  var i = 0;
  var userInt = parseInt(document.getElementById('inputValue').value);
    while(i<userInt) {

        if (i%3 === 0 || i%5 ===0)

            {counter+=i}

          i+=1;
        }
  /*return counter;*/
document.getElementById('displayOne').value = counter;
};




//Euler Problem 2

//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

var e2 = function() {
		var no = 4000000
		var a = 0;
		var b  = 1;
		var c = 0;
		var sum = 0;
		while( c <= no)
		{
				c = a+b;
				a = b;
				b = c;
				if ( c%2 === 0)
					sum = sum + c;
		}
console.log(sum);

}

e2();








//Euler Problem 4

console.log(reverseNumber)




}



var reverseStringFunction = function (originalString)

{
  var stringArray = originalString.split("");
  var stringArrayReverse = stringArray.reverse();
  var reversedString = stringArrayReverse.join("");
    if (reversedString === originalString) {
      console.log("It's a palindrome!")
    }

    else {console.log("It's not a palindrome!")}

    console.log(reversedString);
}

reverseStringFunction("racecar");
